# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'amm-gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1046, 786)
        Dialog.setModal(False)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(10, 760, 351, 16))
        self.label_18.setObjectName("label_18")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 590, 1021, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.result_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.result_layout.setContentsMargins(0, 0, 0, 0)
        self.result_layout.setObjectName("result_layout")
        self.res_box_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.res_box_1.setFont(font)
        self.res_box_1.setText("")
        self.res_box_1.setObjectName("res_box_1")
        self.result_layout.addWidget(self.res_box_1, 1, 2, 1, 1)
        self.cal_m0_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cal_m0_button.setFont(font)
        self.cal_m0_button.setObjectName("cal_m0_button")
        self.result_layout.addWidget(self.cal_m0_button, 5, 3, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.result_layout.addWidget(self.line_2, 0, 0, 1, 6)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.result_layout.addWidget(self.label_19, 1, 0, 1, 1)
        self.res_box_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.res_box_3.setFont(font)
        self.res_box_3.setText("")
        self.res_box_3.setObjectName("res_box_3")
        self.result_layout.addWidget(self.res_box_3, 5, 2, 1, 1)
        self.res_box_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.res_box_2.setFont(font)
        self.res_box_2.setText("")
        self.res_box_2.setObjectName("res_box_2")
        self.result_layout.addWidget(self.res_box_2, 3, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.result_layout.addWidget(self.label_20, 1, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.result_layout.addWidget(self.label_21, 3, 0, 1, 1)
        self.write_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.write_3.setFont(font)
        self.write_3.setObjectName("write_3")
        self.result_layout.addWidget(self.write_3, 5, 1, 1, 1)
        self.write_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.write_1.setFont(font)
        self.write_1.setObjectName("write_1")
        self.result_layout.addWidget(self.write_1, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.result_layout.addWidget(self.label_22, 3, 3, 1, 1)
        self.res_box_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.res_box_5.setFont(font)
        self.res_box_5.setText("")
        self.res_box_5.setObjectName("res_box_5")
        self.result_layout.addWidget(self.res_box_5, 3, 5, 1, 1)
        self.write_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.write_5.setFont(font)
        self.write_5.setObjectName("write_5")
        self.result_layout.addWidget(self.write_5, 3, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.result_layout.addWidget(self.label_23, 5, 0, 1, 1)
        self.res_box_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.res_box_4.setFont(font)
        self.res_box_4.setText("")
        self.res_box_4.setObjectName("res_box_4")
        self.result_layout.addWidget(self.res_box_4, 1, 5, 1, 1)
        self.write_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.write_2.setFont(font)
        self.write_2.setObjectName("write_2")
        self.result_layout.addWidget(self.write_2, 3, 1, 1, 1)
        self.write_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.write_4.setFont(font)
        self.write_4.setObjectName("write_4")
        self.result_layout.addWidget(self.write_4, 1, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.result_layout.addWidget(self.line_4, 6, 0, 1, 6)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(800, 10, 231, 341))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.config_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.config_layout.setContentsMargins(0, 0, 0, 0)
        self.config_layout.setObjectName("config_layout")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.config_layout.addWidget(self.label_11, 10, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.config_layout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.config_layout.addWidget(self.label_10, 10, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.config_layout.addWidget(self.label_4, 1, 0, 1, 1)
        self.low_lim_box = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.low_lim_box.setFont(font)
        self.low_lim_box.setObjectName("low_lim_box")
        self.config_layout.addWidget(self.low_lim_box, 9, 1, 1, 1)
        self.TIME_box = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TIME_box.setFont(font)
        self.TIME_box.setObjectName("TIME_box")
        self.config_layout.addWidget(self.TIME_box, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.config_layout.addWidget(self.label_6, 3, 0, 1, 1)
        self.RATE_box = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RATE_box.setFont(font)
        self.RATE_box.setObjectName("RATE_box")
        self.config_layout.addWidget(self.RATE_box, 0, 1, 1, 1)
        self.FFT_size_box = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FFT_size_box.setFont(font)
        self.FFT_size_box.setObjectName("FFT_size_box")
        self.config_layout.addWidget(self.FFT_size_box, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.config_layout.addWidget(self.label_5, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.config_layout.addWidget(self.label_3, 1, 2, 1, 1)
        self.high_lim_box = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.high_lim_box.setFont(font)
        self.high_lim_box.setObjectName("high_lim_box")
        self.config_layout.addWidget(self.high_lim_box, 10, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.config_layout.addWidget(self.label, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.config_layout.addWidget(self.label_9, 9, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.config_layout.addWidget(self.label_7, 9, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.config_layout.addWidget(self.label_2, 0, 2, 1, 1)
        self.noise_gate_box = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.noise_gate_box.setFont(font)
        self.noise_gate_box.setObjectName("noise_gate_box")
        self.config_layout.addWidget(self.noise_gate_box, 6, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 781, 571))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.visualizer_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.visualizer_layout.setContentsMargins(0, 0, 0, 0)
        self.visualizer_layout.setObjectName("visualizer_layout")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.visualizer_layout.addWidget(self.label_16, 7, 0, 1, 1)
        self.figure_3 = QtWidgets.QGraphicsView(self.gridLayoutWidget_3)
        self.figure_3.setObjectName("figure_3")
        self.visualizer_layout.addWidget(self.figure_3, 7, 1, 1, 1)
        self.figure_2 = QtWidgets.QGraphicsView(self.gridLayoutWidget_3)
        self.figure_2.setObjectName("figure_2")
        self.visualizer_layout.addWidget(self.figure_2, 5, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.visualizer_layout.addWidget(self.label_15, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.visualizer_layout.addWidget(self.label_13, 6, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.visualizer_layout.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.visualizer_layout.addWidget(self.label_14, 8, 1, 1, 1)
        self.figure_1 = QtWidgets.QGraphicsView(self.gridLayoutWidget_3)
        self.figure_1.setObjectName("figure_1")
        self.visualizer_layout.addWidget(self.figure_1, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.visualizer_layout.addWidget(self.label_12, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.visualizer_layout.addWidget(self.line, 3, 2, 6, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(800, 360, 231, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.start_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.start_layout.setContentsMargins(0, 0, 0, 0)
        self.start_layout.setObjectName("start_layout")
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.start_layout.addWidget(self.line_3)
        self.start_test_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_test_button.setFont(font)
        self.start_test_button.setFlat(False)
        self.start_test_button.setObjectName("start_test_button")
        self.start_layout.addWidget(self.start_test_button)
        self.output_browser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_browser.setFont(font)
        self.output_browser.setObjectName("output_browser")
        self.start_layout.addWidget(self.output_browser)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.RATE_box, self.TIME_box)
        Dialog.setTabOrder(self.TIME_box, self.FFT_size_box)
        Dialog.setTabOrder(self.FFT_size_box, self.noise_gate_box)
        Dialog.setTabOrder(self.noise_gate_box, self.low_lim_box)
        Dialog.setTabOrder(self.low_lim_box, self.high_lim_box)
        Dialog.setTabOrder(self.high_lim_box, self.start_test_button)
        Dialog.setTabOrder(self.start_test_button, self.output_browser)
        Dialog.setTabOrder(self.output_browser, self.figure_1)
        Dialog.setTabOrder(self.figure_1, self.figure_2)
        Dialog.setTabOrder(self.figure_2, self.figure_3)
        Dialog.setTabOrder(self.figure_3, self.write_1)
        Dialog.setTabOrder(self.write_1, self.res_box_1)
        Dialog.setTabOrder(self.res_box_1, self.write_2)
        Dialog.setTabOrder(self.write_2, self.res_box_2)
        Dialog.setTabOrder(self.res_box_2, self.write_3)
        Dialog.setTabOrder(self.write_3, self.res_box_3)
        Dialog.setTabOrder(self.res_box_3, self.write_4)
        Dialog.setTabOrder(self.write_4, self.res_box_4)
        Dialog.setTabOrder(self.res_box_4, self.write_5)
        Dialog.setTabOrder(self.write_5, self.res_box_5)
        Dialog.setTabOrder(self.res_box_5, self.cal_m0_button)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_18.setText(_translate("Dialog", "Geo-sonic V1.0 AMM module V1.2 Copyright Siyuan Xu"))
        self.cal_m0_button.setText(_translate("Dialog", "计算堆石体参振质量 m0"))
        self.label_19.setText(_translate("Dialog", "荷载级1"))
        self.label_20.setText(_translate("Dialog", "荷载级4"))
        self.label_21.setText(_translate("Dialog", "荷载级2"))
        self.write_3.setText(_translate("Dialog", "记录结果"))
        self.write_1.setText(_translate("Dialog", "记录结果"))
        self.label_22.setText(_translate("Dialog", "荷载级5"))
        self.write_5.setText(_translate("Dialog", "记录结果"))
        self.label_23.setText(_translate("Dialog", "荷载级3"))
        self.write_2.setText(_translate("Dialog", "记录结果"))
        self.write_4.setText(_translate("Dialog", "记录结果"))
        self.label_11.setText(_translate("Dialog", "上限频率"))
        self.label_8.setText(_translate("Dialog", "触发限"))
        self.label_10.setText(_translate("Dialog", "Hz"))
        self.label_4.setText(_translate("Dialog", "总时长"))
        self.low_lim_box.setText(_translate("Dialog", "10"))
        self.TIME_box.setText(_translate("Dialog", "2"))
        self.label_6.setText(_translate("Dialog", "FFT size"))
        self.RATE_box.setText(_translate("Dialog", "2048"))
        self.FFT_size_box.setText(_translate("Dialog", "700"))
        self.label_5.setText(_translate("Dialog", "毫秒"))
        self.label_3.setText(_translate("Dialog", "秒"))
        self.high_lim_box.setText(_translate("Dialog", "1000"))
        self.label.setText(_translate("Dialog", "采样率"))
        self.label_9.setText(_translate("Dialog", "下限频率"))
        self.label_7.setText(_translate("Dialog", "Hz"))
        self.label_2.setText(_translate("Dialog", "Hz"))
        self.noise_gate_box.setText(_translate("Dialog", "500"))
        self.label_16.setText(_translate("Dialog", "A"))
        self.label_15.setText(_translate("Dialog", "A"))
        self.label_13.setText(_translate("Dialog", "t (ms)"))
        self.label_17.setText(_translate("Dialog", "A"))
        self.label_14.setText(_translate("Dialog", "freqs (Hz)"))
        self.label_12.setText(_translate("Dialog", "t (s)"))
        self.start_test_button.setText(_translate("Dialog", "开始检测"))
        self.output_browser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">欢迎使用Geo-sonic系列软件 AMM振动检测模块 ================= 开始检测之后，请依照本窗口指令进行激励操作</p></body></html>"))

